POST http://localhost:8080/camel/api/process
Content-Type: application/json
Authorization: Basic user password

{
  "userId": 1,
  "title": "This is a title",
  "body": "Blah"
}

###
GET http://localhost:8081/actuator/health
Content-Type: application/json


###
POST localhost:8080/camel/api/process
Content-Type: application/json

{
  "userId": 1,
  "title": "This is a title",
  "body": "Blah"
}

